INSERT INTO product_price_entity (id) VALUES ('1');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('4.90', '10', '1');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('3.90', '10', '1');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('2.90', '10', '1');
INSERT INTO product_price_entity (id) VALUES ('2');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('2.55', '5', '2');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('2.45', '5', '2');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('2.35', '5', '2');
INSERT INTO product_price_entity (id) VALUES ('3');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('3.20', '5', '3');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('3.66', '5', '3');
INSERT INTO product_price_entity_stock_prices (price, stock_quantity, product_price_entity_id) VALUES ('3.45', '5', '3');